name: starter_mvvm_cubit
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  dio: ^5.0.0
  easy_localization: ^3.0.1
  equatable: ^2.0.3
  flex_color_scheme: ^6.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_screenutil: ^5.6.1
  flutter_svg: ^2.0.2
  get_it: ^7.2.0
  google_fonts: ^4.0.3
  intl: ^0.17.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  path_provider: ^2.0.12
  sembast: ^3.4.0+6
  shared_preferences: ^2.0.17
  uni_links: ^0.5.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.18
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/

#use these commands in order to generate new splash screen
#flutter clean
#flutter pub get
#flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  color_dark: "#121212"
  image_dark: assets/images/logo.png
