name: starter_mvvm_cubit
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  dio: ^4.0.6
  easy_localization: ^3.0.1
  equatable: ^2.0.3
  flex_color_scheme: ^5.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^1.1.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  intl: ^0.17.0
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  path_provider: ^2.0.11
  sembast: ^3.2.0+1
  shared_preferences: ^2.0.15
  uni_links: ^0.5.1

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.3+1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/


#use these commands in order to generate new splash screen
#flutter clean
#flutter pub get
#flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  color_dark: "#121212"
  image_dark: assets/images/logo.png

